name: Publish AnalyzeMFT Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine 

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package to PyPi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_ACCESS_TOKEN }}
      run: |
        twine upload dist/*

    - name: Clean up
      run: |
        rm -rf dist
        rm -rf build
        rm -rf *.egg-info
